modLoader="javafml"
loaderVersion="[41,)"
license="GNU Affero General Public License v3.0"
issueTrackerURL="https://github.com/Viola-Siemens/Villager-Armor-Layer/issues"

[[mods]]
modId="villagerarmor"
version="${file.jarVersion}"
displayName="Villager Armor Layer"
logoFile="logo.png"
credits="Liu Dongyu"
authors="Hexagram"
description='''
With this mod, villagers and illagers' armor layer will be rendered.
'''

[[dependencies.villagerarmor]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.villagerarmor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
